version: '3'
services:
  web:
    image: quay.io/buildo/cryptonite:web-latest
    ports:
     - "8080:80"
  api:
    image: quay.io/buildo/cryptonite:api-latest
    environment:
      - CRYPTONITE_HOST=0.0.0.0
